In [1]:
import numpy as np
np.random.seed(0)

In [13]:
np.random.seed(0)
values = np.random.randint(1, 10, size=5)
values

array([6, 1, 4, 4, 8])

In [17]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [18]:
big_array = np.random.randint(1, 100, size=1000000)
big_array

array([10, 84, 22, ..., 70, 91, 87])

In [19]:
%timeit compute_reciprocals(big_array)

4.43 s ± 119 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
%timeit (1.0 / big_array)

9.33 ms ± 170 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
%timeit np.arange(5)/ np.arange(1, 6)

5.87 µs ± 290 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
 np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [24]:
x = np.arange(9).reshape((3, 3))
%timeit 2 ** x

2.31 µs ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# Simple Linear Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)
